/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-library-conventions")
    id("maven-publish")
}

// TODO: replace with use of "com.github.ben-manes.versions" plugin?
apply<DependencyUpdatePlugin>()

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.org.json)
    testImplementation(kotlin("test"))
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
    options.release = 17
}

group = "ktfind" // should this be "xfind" or "xfind.ktfind"?
version = "0.1.0-SNAPSHOT"

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["kotlin"])
        }
    }
    repositories {
        mavenLocal()
    }
}
