requires 'perl', '5.44';
requires 'DateTime::Format::DateParse', '0.05';
requires 'Path::Class', '0.37';
requires 'JSON::PP', '4.18';
requires 'Scalar::Util', '1.70';

# Group dependencies by environment phase
on 'test' => sub {
    requires 'Devel::Camelcadedb';
};