# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in rbfind-new.gemspec
gemspec

gem 'rake', '~> 13.2.1'

gem 'rbs', '~> 3.9.1'

gem 'test-unit', '~> 3.6.7'

gem 'rubocop', '~> 1.75'

ruby '3.4.2'
