# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in rbfind-new.gemspec
gemspec

gem 'rake', '~> 13.3.1'

gem 'rbs', '~> 3.10.2'

gem 'test-unit', '~> 3.7.7'

gem 'rubocop', '~> 1.82.1'

ruby '3.4.5'
