package gofind

func GetFindOptions() *FindOptions {
	return &FindOptions{
		[]*FindOption{
			{"", "archivesonly", "Find only archive files"},
			{"", "debug", "Set output mode to debug"},
			{"Z", "excludearchives", "Exclude archive files (bz2, gz, tar, zip)*"},
			{"", "excludehidden", "Exclude hidden files and directories*"},
			{"h", "help", "Print this usage and exit"},
			{"z", "includearchives", "Include archive files (bz2, gz, tar, zip)"},
			{"", "includehidden", "Include hidden files and directories"},
			{"", "in-archiveext", "Specify extension for archive files to include in find"},
			{"", "in-archivefilepattern", "Specify name pattern for archive files to include in find"},
			{"d", "in-dirpattern", "Specify name pattern for directories to include in find"},
			{"x", "in-ext", "Specify extension for files to include in find"},
			{"f", "in-filepattern", "Specify name pattern for files to include in find"},
			{"t", "in-filetype", "File type to find (text, binary)"},
			{"", "maxlastmod", "Find files with lastmod less than or equal to maxlastmod"},
			{"", "maxsize", "Find files with size <= maxsize"},
			{"", "minlastmod", "Find files with lastmod greater than or equal to minlastmod"},
			{"", "minsize", "Find files with size >= minsize"},
			{"R", "norecursive", "Do not find recursively (no subdirectories)"},
			{"", "out-archiveext", "Specify extension for archive files to exclude from find"},
			{"", "out-archivefilepattern", "Specify name pattern for archive files to exclude from find"},
			{"D", "out-dirpattern", "Specify name pattern for directories to exclude from find"},
			{"X", "out-ext", "Specify extension for files to exclude from find"},
			{"F", "out-filepattern", "Specify name pattern for files to exclude from find"},
			{"T", "out-filetype", "File type not to find (text, binary)"},
			{"", "printdirs", "Generate a list of the matching directories after finding"},
			{"", "printfiles", "Generate a list of the matching files after finding"},
			{"r", "recursive", "Find recursively through subdirectories*"},
			{"", "settings-file", "A path to a JSON file with specified find settings"},
			{"", "sort-by", "Sort by: PATH, NAME, TYPE, SIZE, LASTMOD"},
			{"", "sort-ascending", "Sort results in ascending order*"},
			{"", "sort-casesensitive", "Sort results case-sensitive*"},
			{"", "sort-caseinsensitive", "Sort results case-insensitive"},
			{"", "sort-descending", "Sort results in descending order"},
			{"v", "verbose", "Set output mode to verbose"},
			{"V", "version", "Print version and exit"},
		},
	}
}
