package gofind

func GetFindOptions() *FindOptions {
	return &FindOptions{
		[]*FindOption{
			&FindOption{"a", "allmatches", "Capture all matches*"},
			&FindOption{"", "archivesonly", "Find only archive files"},
			&FindOption{"", "debug", "Set output mode to debug"},
			&FindOption{"e", "encoding", "Set the encoding to use with text files (default: \"utf-8\")"},
			&FindOption{"", "excludehidden", "Exclude hidden files and directories*"},
			&FindOption{"1", "firstmatch", "Capture only the first file+pattern match"},
			&FindOption{"h", "help", "Print this usage and exit"},
			&FindOption{"", "includehidden", "Include hidden files and directories"},
			&FindOption{"", "in-archiveext", "Specify extension for archive files to include in find"},
			&FindOption{"", "in-archivefilepattern", "Specify name pattern for archive files to include in find"},
			&FindOption{"d", "in-dirpattern", "Specify name pattern for directories to include in find"},
			&FindOption{"x", "in-ext", "Specify extension for files to include in find"},
			&FindOption{"f", "in-filepattern", "Specify name pattern for files to include in find"},
			&FindOption{"t", "in-filetype", "File type to find (text, binary)"},
			&FindOption{"", "in-linesafterpattern", "Specify pattern to find the \"lines-after\" lines on"},
			&FindOption{"", "in-linesbeforepattern", "Specify pattern to find the \"lines-before\" lines on"},
			&FindOption{"L", "linesafter", "Number of lines to include after every matched line (default: 0)"},
			&FindOption{"", "linesaftertopattern", "Specify pattern to collect lines after up to where pattern matched"},
			&FindOption{"", "linesafteruntilpattern", "Specify pattern to collect lines after until pattern matched"},
			&FindOption{"l", "linesbefore", "Number of lines to include before every matched line (default: 0)"},
			&FindOption{"", "listdirs", "Generate a list of the matching directories after finding"},
			&FindOption{"", "listfiles", "Generate a list of the matching files after finding"},
			&FindOption{"", "listlines", "Generate a list of the matching lines after finding"},
			&FindOption{"w", "maxlinelength", "Max length of line of result to print out (default: 150)"},
			&FindOption{"m", "multilineoption-REMOVE", "Find files as single multi-line content block"},
			&FindOption{"P", "noprintmatches", "Suppress printing of find results to stdout"},
			&FindOption{"R", "norecursive", "Do not find recursively (no subdirectories)"},
			&FindOption{"Z", "nofindarchives", "Do not find archive files (bz2, gz, tar, zip)*"},
			&FindOption{"", "out-archiveext", "Specify extension for archive files to exclude from find"},
			&FindOption{"", "out-archivefilepattern", "Specify name pattern for archive files to exclude from find"},
			&FindOption{"D", "out-dirpattern", "Specify name pattern for directories to exclude from find"},
			&FindOption{"X", "out-ext", "Specify extension for files to exclude from find"},
			&FindOption{"F", "out-filepattern", "Specify name pattern for files to exclude from find"},
			&FindOption{"T", "out-filetype", "File type not to find (text, binary)"},
			&FindOption{"", "out-linesafterpattern", "Specify pattern to filter the \"lines-after\" lines on"},
			&FindOption{"", "out-linesbeforepattern", "Specify pattern to filter the \"lines-before\" lines on"},
			&FindOption{"p", "printmatches", "Print find results to stdout*"},
			&FindOption{"r", "recursive", "Find recursively through subdirectories*"},
			&FindOption{"s", "findpattern", "Specify find pattern"},
			&FindOption{"z", "findarchives", "Find archive files (bz2, gz, tar, zip)"},
			&FindOption{"", "settings-file", "A path to a JSON file with specified find settings"},
			&FindOption{"u", "uniquelines", "Save only find results with unique lines from previous results"},
			&FindOption{"v", "verbose", "Set output mode to verbose"},
			&FindOption{"V", "version", "Print version and exit"},
		},
	}
}
