class Object
  def find_main: () -> void

  def handle_find_error: (StandardError err, bool colorize, RbFind::FindOptions options) -> void

  def find: (RbFind::FindOptions options, RbFind::FindSettings settings) -> void
end
