################################################################################
#
# config.sh
#
# The common configuration for bash scripts
#
################################################################################

########################################
# Configuration
########################################

# XFIND_PATH defaults to $HOME/src/xfind if not defined as env var
if [ -z "$XFIND_PATH" ]; then
    if [ -n "$XFINDPATH" ]; then
        XFIND_PATH=$XFINDPATH
    else
        XFIND_PATH=$HOME/src/xfind
    fi
fi
XFIND_BIN_PATH=$XFIND_PATH/bin
XFIND_SHARED_PATH=$XFIND_PATH/shared
XFIND_TEST_FILE_PATH=$XFIND_SHARED_PATH/testFiles

# Language roots
XFIND_BASH_PATH=$XFIND_PATH/bash
XFIND_C_PATH=$XFIND_PATH/c
XFIND_CLOJURE_PATH=$XFIND_PATH/clojure
XFIND_CPP_PATH=$XFIND_PATH/cpp
XFIND_CSHARP_PATH=$XFIND_PATH/csharp
XFIND_DART_PATH=$XFIND_PATH/dart
XFIND_ELIXIR_PATH=$XFIND_PATH/elixir
XFIND_FSHARP_PATH=$XFIND_PATH/fsharp
XFIND_GO_PATH=$XFIND_PATH/go
XFIND_GROOVY_PATH=$XFIND_PATH/groovy
XFIND_HASKELL_PATH=$XFIND_PATH/haskell
XFIND_JAVA_PATH=$XFIND_PATH/java
XFIND_JAVASCRIPT_PATH=$XFIND_PATH/javascript
XFIND_KOTLIN_PATH=$XFIND_PATH/kotlin
XFIND_OBJC_PATH=$XFIND_PATH/objc
# XFIND_OCAML_PATH=$XFIND_PATH/ocaml
XFIND_PERL_PATH=$XFIND_PATH/perl
XFIND_PHP_PATH=$XFIND_PATH/php
XFIND_POWERSHELL_PATH=$XFIND_PATH/powershell
XFIND_PYTHON_PATH=$XFIND_PATH/python
XFIND_RUBY_PATH=$XFIND_PATH/ruby
XFIND_RUST_PATH=$XFIND_PATH/rust
XFIND_SCALA_PATH=$XFIND_PATH/scala
XFIND_SWIFT_PATH=$XFIND_PATH/swift
XFIND_TYPESCRIPT_PATH=$XFIND_PATH/typescript

# Language version roots
BASHFIND_PATH=$XFIND_BASH_PATH/bashfind
CFIND_PATH=$XFIND_C_PATH/cfind
CLJFIND_PATH=$XFIND_CLOJURE_PATH/cljfind
CPPFIND_PATH=$XFIND_CPP_PATH/cppfind
CSFIND_PATH=$XFIND_CSHARP_PATH/csfind
DARTFIND_PATH=$XFIND_DART_PATH/dartfind
EXFIND_PATH=$XFIND_ELIXIR_PATH/exfind
FSFIND_PATH=$XFIND_FSHARP_PATH/fsfind
GOFIND_PATH=$XFIND_GO_PATH/gofind
GROOVYFIND_PATH=$XFIND_GROOVY_PATH/groovyfind
HSFIND_PATH=$XFIND_HASKELL_PATH/hsfind
JAVAFIND_PATH=$XFIND_JAVA_PATH/javafind
JSFIND_PATH=$XFIND_JAVASCRIPT_PATH/jsfind
KTFIND_PATH=$XFIND_KOTLIN_PATH/ktfind
OBJCFIND_PATH=$XFIND_OBJC_PATH/objcfind
# OCAMLFIND_PATH=$XFIND_OCAML_PATH/mlfind
# MLFIND_PATH=$XFIND_OCAML_PATH/mlfind
PLFIND_PATH=$XFIND_PERL_PATH/plfind
PHPFIND_PATH=$XFIND_PHP_PATH/phpfind
PS1FIND_PATH=$XFIND_POWERSHELL_PATH/ps1find
PYFIND_PATH=$XFIND_PYTHON_PATH/pyfind
RBFIND_PATH=$XFIND_RUBY_PATH/rbfind
RSFIND_PATH=$XFIND_RUST_PATH/rsfind
SCALAFIND_PATH=$XFIND_SCALA_PATH/scalafind
SWIFTFIND_PATH=$XFIND_SWIFT_PATH/swiftfind
TSFIND_PATH=$XFIND_TYPESCRIPT_PATH/tsfind
