module RbFind
  # FindFile - encapsulates a file to be found
  class FileResult
    @containers: Array[Pathname]
    @path: Pathname
    @file_type: FileType
    @file_size: Integer
    @last_mod: nil | Time

    attr_accessor containers: Array[Pathname]
    attr_reader path: Pathname
    attr_reader file_type: FileType
    attr_reader file_size: Integer
    attr_reader last_mod: nil | Time

    CONTAINER_SEPARATOR: "!"

    def initialize: (Pathname path, FileType file_type, Integer file_size, nil | Time last_mod) -> void

    def dir_name: () -> String

    def file_name: () -> String

    def relative_path: () -> Pathname

    def to_s: () -> String
  end
end
