module RbFind
  # FileUtil - file utility functions
  module FileUtil
    DOT_DIRS: Array["." | ".." | "./" | "../"]

    def self?.dot_dir?: (Pathname file_path) -> bool

    def self?.get_extension: (Pathname | String file_path) -> String

    def self?.hidden_name?: (String file_name) -> bool

    def self?.hidden_path?: (Pathname file_path) -> bool

    def self?.path_elems: (Pathname file_path) -> Array[String]

    def self?.elem_count: (Pathname file_path) -> Integer
  end
end
