module RbFind

  class FileResultFormatter
    @settings: FindSettings
    @file_types: FileTypes

    attr_reader settings: FindSettings

    def initialize: (FindSettings settings) -> void

    def colorize: (String str, Integer match_start_index, Integer match_end_index) -> String

    def format_dir_path_with_color: (Pathname path) -> String

    def format_dir_path: (Pathname path) -> String

    def format_file_name_with_color: (Pathname file_name) -> String

    def format_file_name: (Pathname file_name) -> String

    def format_path: (Pathname path) -> String

    def format_file_result: (FileResult file_result) -> String

  end
end
