module RbFind

  class FileResultSorter
    @settings: FindSettings

    attr_reader settings: FindSettings

    def initialize: (FindSettings settings) -> void

    def sort: (Array[FileResult] file_results) -> void

    private

    def get_file_result_comparator: -> Proc

  end
end
