module RbFind
  # FindOptions - parses CLI args into settings, generates usage string
  class FindOptions
    @options: Array[FindOption]
    @bool_action_dict: Hash[Symbol, Proc]
    @str_action_dict: Hash[Symbol, Proc]
    @int_action_dict: Hash[Symbol, Proc]
    @long_arg_dict: Hash[String, Symbol]

    attr_reader options: Array[FindOption]

    def initialize: () -> void

    def arg_hash_from_args:(Array[String] args) -> Hash[Symbol, untyped]

    def update_settings_from_arg_hash: (FindSettings settings, Hash[Symbol, untyped] args_hash) -> void

    def update_settings_from_args: (FindSettings settings, Array[String] args) -> void

    def find_settings_from_args: (Array[String] args) -> FindSettings

    def update_settings_from_json: (FindSettings settings, String json) -> void

    def update_settings_from_file: (FindSettings settings, String file_path) -> void

    def get_usage_string: () -> String

    def usage: () -> void

    private

    def set_actions: () -> void

    def set_options_from_json: () -> void
  end
end
