module RbFind
  # FindOption - encapsulates a CLI find option
  class FindOption
    @short_arg: String
    @long_arg: String
    @desc: String
    @arg_type: ArgTokenType

    attr_reader short_arg: String
    attr_reader long_arg: String
    attr_reader desc: String
    attr_reader arg_type: ArgTokenType

    def initialize: (String short_arg, String long_arg, String desc, ArgTokenType arg_type) -> void

    def sort_arg: () -> String
  end
end
